#!/bin/sh

if [ ! -d .git ]; then
    echo "must be run from root of advent-of-code repository" >&2
    exit 1
fi

DAY=$(if [ $# != 1 ]; then date +%-d; else echo $1; fi)

NAME="$(printf "day%02d" "$DAY")"
cargo new --bin "$NAME"
mkdir "$NAME/input"
cp boilerplate.rs "$NAME/src/main.rs"
