#!/bin/bash

if [ ! -d .git ]; then
    echo "must be run from root of advent-of-code repository" >&2
    exit 1
fi

if [ ! -f ".env" ]; then
	echo ".env does not exist."
	exit 1
fi

source .env
if [ ! -n "$KEY" ]; then
	echo ".env file doesn't contain KEY=<key>."
	exit 1
fi

YEAR=$(date +%Y)
DAY=$(date +%-d)

echo "Downloading puzzle input for $YEAR, day $DAY..."

URL="https://adventofcode.com/$YEAR/day/$DAY/input"
NAME="$(printf "day%02d/input/input.txt" $DAY)"

curl -A "Private script by endden@gmail.com" --cookie "session=$KEY" $URL >$NAME
